### PR TITLE
Support named parameter 'type' in the Cast attribute.

### PR DESCRIPTION
**Pull request by mickverm**
When using `#[Cast(type: 'int')]` for example, I always ran into the following exception:

```
Undefined array key 0
vendor\wendelladriel\laravel-lift\src\Concerns\CastValues.php :106
```

### CODE REVIEW

**Review by WendellAdriel — CHANGES_REQUESTED** [review]
Thanks for the contribution!

Can you update one or two datasets to not use the named parameter just so we can have use cases validated against using and not using the named parameter, please?

**Comment by mickverm** [comment]
Change, I was maybe a bit too eager in adding `type`. 😛

**Comment by WendellAdriel** [comment]
> Pint errors are fixed, now PHPStan is complaining 😅

😅 😅 😅 
Can you help me with that as well, please?

**Comment by mickverm** [comment]
Fixed PHPStan errors as well!

**Comment by mickverm** [comment]
The tests were also failing for me locally, but never via Github actions, until now...
The failing tests are not related to this MR, since I can reproduce them locally on the main branch as well.

**Comment by WendellAdriel** [comment]
> The tests were also failing for me locally, but never via Github actions, until now... The failing tests are not related to this MR, since I can reproduce them locally on the main branch as well.

Thanks for taking a look at it.
Weird that the tests were not failing before 😓 

I'll see if I have some time next week to check on the tests

**Comment by mickverm** [comment]
I fixed the tests, I also had to make a small change to make `toBeFileWithContent()` pass on Windows.

**Review by WendellAdriel — APPROVED** [review]
Thanks a lot for all the effort in this PR! 💪

**Pull request merged**
