### PR TITLE
fix having stale properties after refreshing a model

### PR DESCRIPTION
**Pull request by vovarudomanenko**
Lift doesn't refill model attributes after refreshing a model.
In this PR I have fixed it and added a test.

### CODE REVIEW

**Comment by vovarudomanenko** [comment]
Actually I didn't fully fixed the issue. I only fixed refreshement of fields that have default value in the database e.g. `->default(999)`. But refreshemnt for all other fields is broken. See example below

```php
Schema::create('category_refresheds', function (Blueprint $table) {
    $table->id();
    $table->string('title');
    $table->integer('sort')->default(9999);
    $table->timestamps();
});

class CategoryRefreshed extends Model
{
    use Lift;

    #[PrimaryKey]
    public int $id;

    #[Fillable]
    public string $title;

    #[Fillable]
    public int $sort;
}

($discount = new Category(['title' => 'test'))->save();
$discount->title = 'updated';
$discount->save()->refresh();
echo $discount->title; // outputs 'test'. Not correct!

$discount->sort; // outputs 999. Correct!


```

**Comment by vovarudomanenko** [comment]
fixed it and updated a the test

**Comment by vovarudomanenko** [comment]
Added a better fix that overwrites `setRawAttributes` method instead of `refresh` method

**Review by WendellAdriel — APPROVED** [review]
Nice catch and fix here, thank you so much! 🔥 💪

**Pull request merged**
